blank_issues_enabled: true
contact_links:
  - name: Bit Core Security Policy
    url: https://github.com/bit/bit/blob/master/SECURITY.md
    about: View security policy
  - name: Bit Core Developers
    url: https://bitcoincore.org
    about: Bit Core homepage
