.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bit_qt test_bit_qt
clean: FORCE
	$(MAKE) -C .. bit_qt_clean test_bit_qt_clean
check: FORCE
	$(MAKE) -C .. test_bit_qt_check
bit-qt bit-qt.exe: FORCE
	 $(MAKE) -C .. bit_qt
apk: FORCE
	$(MAKE) -C .. bit_qt_apk
