#ifndef BIT_CHAINPARAMSSEEDS_H
#define BIT_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the bit network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01, 0x04, 0x2D, 0x0E, 0x32, 0x1F, 0xF6, 0x52,  // 45.14.50.31:20982 (mainnet)
    0x01, 0x04, 0x33, 0x59, 0xAC, 0x4C, 0xF6, 0x52,  // 51.89.172.76:20982 (mainnet)
    0x01, 0x04, 0x33, 0x59, 0xAC, 0x61, 0xF6, 0x52,  // 51.89.172.97:20982 (mainnet)
};

static const uint8_t chainparams_seed_test[] = {
};
#endif // BIT_CHAINPARAMSSEEDS_H
